### ISSUE TITLE
Can it be used with a Rails API backend?

### ISSUE THREAD

**Issue by jgamedev** [terminalvelocity/ember-cli-seeds-scaffold#7]
I like this scaffold because apparently it uses Semantic-UI by default, but for this project I'm not using a Node.JS backend.

Can I still use it?

**Comment by jhliberty** [comment]
I don't see why not - the only thing you should really have to change with this is the adapter (or change what port your rails API is using to 1776)

**Comment by jhliberty** [comment]
Let me know if you have any other questions and feel free to join us on [gitter](https://gitter.im/terminalvelocity/seeds.js )
